CREATE TABLE `wx_office_account` (
                                     `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                                     `classify` tinyint(1) DEFAULT '1' COMMENT '授权资质类型：1=服务商模式，2=个人模式',
                                     `department` int(11) NOT NULL DEFAULT '0' COMMENT '客服部门',
                                     `type_app` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1.微信公众号2.小程序',
                                     `is_used` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '1.可用2.不可用',
                                     `gid` int(11) unsigned DEFAULT '0' COMMENT '微信分组ID',
                                     `appid` varchar(100) NOT NULL COMMENT 'appid',
                                     `platform` tinyint(2) unsigned DEFAULT '1' COMMENT '服务商ID',
                                     `refresh_token` varchar(255) NOT NULL,
                                     `name` varchar(100) NOT NULL COMMENT '昵称',
                                     `head_img` text NOT NULL COMMENT '头像',
                                     `original` varchar(100) NOT NULL COMMENT '第三方授权的名称',
                                     `com_main_body` varchar(255) NOT NULL COMMENT '主体名称',
                                     `alias` varchar(255) DEFAULT NULL COMMENT '微信号',
                                     `headimg` varchar(255) DEFAULT NULL COMMENT '二微码',
                                     `status` tinyint(3) NOT NULL COMMENT '1.正常2.取消',
                                     `level` varchar(255) NOT NULL,
                                     `type` tinyint(3) NOT NULL DEFAULT '0' COMMENT '公众号等级（订阅，是否认证）',
                                     `token` varchar(255) NOT NULL DEFAULT '',
                                     `encodingaeskey` varchar(255) NOT NULL DEFAULT '',
                                     `account_id` int(11) NOT NULL DEFAULT '0',
                                     `create_time` int(11) NOT NULL,
                                     `update_time` int(11) NOT NULL,
                                     `func_info` text COMMENT '权限集列表',
                                     `release` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '发布版本的次数',
                                     `version` varchar(50) NOT NULL DEFAULT '0' COMMENT '小程序版本号',
                                     `audit_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0审核成功，1.审核被拒绝2.审核中，3.已撤回',
                                     `is_frozen` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1不冻结 2 冻结了',
                                     `audit_time` varchar(255) DEFAULT NULL COMMENT '审核shi jain',
                                     `domain_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0.未添加1.添加',
                                     `daily_limit` int(10) NOT NULL DEFAULT '0' COMMENT '当日最大生成链接数',
                                     `used` int(10) NOT NULL DEFAULT '0' COMMENT '当已经使用链接数',
                                     `remain` int(10) NOT NULL DEFAULT '0' COMMENT '当日剩余链接数',
                                     `remain_time` int(10) NOT NULL DEFAULT '0' COMMENT '小程序链接没有可用测试的时间',
                                     `delect_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否删除1正常2删除',
                                     `product_ids` varchar(255) NOT NULL COMMENT '小程序匹配商品',
                                     `h5_ids` varchar(255) DEFAULT NULL COMMENT '小程序匹配H5',
                                     `customer_phone` varchar(255) DEFAULT NULL COMMENT '客服名称',
                                     `customer_img` varchar(255) DEFAULT NULL COMMENT '客服头像',
                                     `shop_style` tinyint(2) NOT NULL DEFAULT '1' COMMENT '1.枫叶小店样式2.淘积木样式',
                                     `pay_priTmplId` varchar(255) DEFAULT NULL COMMENT '订阅支付模版参数',
                                     `home_style_type` varchar(255) DEFAULT NULL COMMENT '小程序首页风格类型：1、2、3',
                                     `wait_pay_priTmplId` varchar(255) DEFAULT NULL COMMENT '订阅待支付模板参数',
                                     `express_priTmplId` varchar(255) DEFAULT NULL COMMENT '订阅发货模板参数',
                                     `customer_status` tinyint(2) NOT NULL DEFAULT '2' COMMENT '1.开启2.关闭',
                                     `trace_express` tinyint(2) NOT NULL DEFAULT '2' COMMENT '物流组件1.开启2.关闭',
                                     `after_sales_days` smallint(10) NOT NULL DEFAULT '15' COMMENT '售后服务天数默认15天',
                                     `upload_code` text NOT NULL COMMENT '私有化',
                                     PRIMARY KEY (`id`) USING BTREE,
                                     KEY `status` (`status`) USING BTREE,
                                     KEY `remain` (`remain`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8 COMMENT='授权公众号列表';