// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	office "zero-scaffold/office/internal/handler/office"
	"zero-scaffold/office/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/index",
				Handler: office.ListHandler(serverCtx),
			},
		},
	)
}
